### PR TITLE
add mri instance

### PR DESCRIPTION
**Pull request by yuliumitre**

### CODE REVIEW

**Comment by lpdecelles** [comment]
@yuliumitre I am seeing these errors when I try to build. Am I missing something?

image

**Comment by yuliumitre** [comment]
@lpdecelles I don't see the build error you saw. Not sure why sushi cares about the codes in the value sets. Although, there are some errors related to the MRI example on QA report. I will try to figure out and fix those errors.

**Comment by yuliumitre** [comment]
@lpdecelles I fixed the errors in qa report. Can you try to rebuild and see if it fixes your build errors?

**Comment by lpdecelles** [comment]
I can build now. I am reviewing. Thanks!

**Pull request merged**
